// #include "cholesky.cpp"
#include "densematrix.cpp"
#include "factorization.cpp"
#include "functions.cpp"
// #include "gaussjordan.cpp"
// #include "qr.factorization.cpp"
//#include "readwrite.cpp"
//#include "scalarfunctions.cpp"
#include "simplesolver.cpp"
