#include "iterativesolver.cpp"
// #include "cgm.cpp"
// #include "crm.cpp"
// #include "pcrm.cpp"
// #include "minres.cpp"
// #include "herzogsoodhalter.cpp"
// #include "resdes.cpp"
#include "sparsesolver.cpp"
#include "systemsolver.cpp"
#include "systemsparsesolver.cpp"
#include "nullspace.cpp"
